services:
  db:
    image: postgres:15
    container_name: ordering_food_db
    ports:
      - "5432:5432"
    env_file:
      - .env

  app:
    build:
      context: .
    env_file:
      - .env
    container_name: apps_ordering_food
    ports:
      - 9999:8000
    depends_on:
      - db
    command: >
      sh -c "alembic upgrade head &&
      gunicorn src.main:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind=0.0.0.0:8000"